name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
    - name: yarn install and build 
      run: |
        yarn install
        yarn build
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
